swagger: '2.0'
info:
  description: This is a test for SKOuchi's AD420 class
  version: 1.0.0
  title: AD420 API Skouchi
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v2
tags:
  - name: AD420
    description: First API created by SKOuchi
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: API AD420
    description: API Access AD420
  - name: user
    description: Operations about user
    externalDocs:
      description: N/A
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /user/:
    post:
      tags:
        - user
      summary: Create a new user
      description: Add a user
      operationId: addUser
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: User needs to be added
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        '405':
          description: Invalid input
  '/user/{userId}':
    get:
      tags:
        - user
      summary: Find user by ID
      description: Returns a single user
      operationId: getuserById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/user'
        '400':
          description: Invalid ID supplied
        '404':
          description: user not found
    put:
      tags:
        - user
      summary: Update an existing user
      description: Update an existing user by ID
      operationId: putuserById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: userId
          in: path
          description: ID of user to update
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/user'
        '400':
          description: Invalid ID supplied
        '404':
          description: user not found
    delete:
      tags:
        - user
      summary: Deletes a user
      description: ''
      operationId: deleteUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: userId
          in: path
          description: User id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
  '/user/{userId}/task':
    get:
      tags:
        - task
      summary: Get user by task
      description: Get user by task
      operationId: getTask
      produces:
        - application/xml
        - application/json
      consumes:
        - application/xml
        - application/json
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          type: integer
          format: int64
        - name: task
          in: query
          description: Find task
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/task'
        '400':
          description: Invalid ID supplied
        '404':
          description: user not found
    post:
      tags:
        - task
      summary: Create a new task for user
      description: Create a new task for user
      operationId: addTask
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - name: task
          in: body
          description: Id of user with task
          required: true
          schema:
            $ref: '#/definitions/task'
      responses:
        '405':
          description: Invalid input
  '/user/{userId}/task/{taskId}':
    get:
      tags:
        - task
      summary: Get user by task
      description: Get user by task
      operationId: getTaskById
      produces:
        - application/xml
        - application/json
      consumes:
        - application/xml
        - application/json
      parameters:
        - name: userId
          in: path
          description: User Id
          required: true
          type: integer
          format: int64
        - name: taskName
          in: query
          description: Find task
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/task'
        '400':
          description: Invalid ID supplied
        '404':
          description: user not found
    put:
      tags:
        - task
      summary: Update user task
      description: ''
      operationId: updateTask
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: updateTask
          description: Update user by task
          required: true
          schema:
            $ref: '#/definitions/task'
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - task
      summary: Deletes a task
      description: ''
      operationId: deleteTask
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: taskId
          in: path
          description: task id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
definitions:
  task:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      complete:
        type: boolean
        default: false
    xml:
      name: Task
  user:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      task:
        type: array
        xml:
          name: task
          wrapped: true
        items:
          $ref: '#/definitions/task'
    xml:
      name: User
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
